Fixing errors caused by new core
Qbox-project/qbx_newsjob pull request #6
Opened 2023-11-18 22:56 UTC by dusan01

## Description

There was an issue when you started a resource about core objects, so this fixes it, I also moved the config to a folder and adjusted the code a little bit to match the new format and more user-friendly names.

There is still an error for the camera.lua file, I was unable to determine what's causing it, so if someone can point me in the right direction, I will be more than happy to fix that issue too.

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-11-24 00:50 UTC, alberttheprince commented
Tested these fixes on live server, it seems to fix the job and make it work with Qbox. However, the resource itself seems lackluster/lacking in design. Maybe potential for reworking slightly?

2023-11-24 05:27 UTC, Manason requested changes

2023-11-24 05:27 UTC, Manason commented on client/camera.lua
> +	if not ( IsPedSittingInAnyVehicle(cache.ped) ) then
```suggestion
	if not cache.vehicle then
```

2023-11-24 05:27 UTC, Manason commented on client/camera.lua
> +RegisterNetEvent('qbx_newsjob:client:toggleCam', function()
This seems like it should be a callback rather than an event

2023-11-24 05:27 UTC, Manason commented on client/camera.lua
> +				SetCurrentPedWeapon(cache.ped, joaat(`WEAPON_UNARMED`), true)
```suggestion
				SetCurrentPedWeapon(cache.ped, `WEAPON_UNARMED`, true)
```
backticks already convert a string to a hash

2023-11-24 05:27 UTC, Manason commented on client/camera.lua
> +					while movcamera and not IsEntityDead(cache.ped) and (GetVehiclePedIsIn(cache.ped) == vehicle) and true do
```suggestion
					while movcamera and not IsEntityDead(cache.ped) and cache.vehicle == vehicle) do
```

2023-11-24 05:27 UTC, Manason commented on client/camera.lua
> +					local vehicle = GetVehiclePedIsIn(cache.ped)
```suggestion
					local vehicle = cache.vehicle
```

2023-11-24 05:27 UTC, Manason commented on client/camera.lua
> +RegisterNetEvent('qbx_newsjob:client:toggleBMic', function()
Seems like it should be a callback

2023-11-24 05:27 UTC, Manason commented on client/main.lua
> +            return
How much of this is duplicate code with spawning a vehicle? Consider extracting a function

2023-11-24 05:27 UTC, Manason commented on client/main.lua
> +                if #(pos - vec3(config.locations.helicopterStorageEntrance.coords.xyz)) < 1.5 then
Why are these distance checks needed? Seems like these zones should be created once; and not created and destroyed within a loop. Could clean them up on resource stop and create them on resource start though.

2023-11-24 05:27 UTC, Manason commented on server/main.lua
> +    if Player.PlayerData.job.name ~= 'reporter' then return end
consider extracting duplicate code into a function "isAReporter"

2023-11-24 11:37 UTC, dusan01 commented
I do agree with both of you, this does actually need a good rewrite, but with this PR I just wanted to convert it and make it work, before doing the actual rewrite to make it better.

2023-11-24 15:49 UTC, Manason commented on client/main.lua
> +                if #(pos - vec3(config.locations.helicopterStorageEntrance.coords.xyz)) < 1.5 then
The other comments are fine to leave for another PR, but this one has to do with code introduced here and should be addressed.

2023-11-25 00:36 UTC, Manason approved these changes

2023-11-25 18:22 UTC, MafewTM approved these changes

2023-11-25 18:22 UTC, merged